[build]
publish = "dist"
command = "npm run build"

[functions]
directory = "backend"
node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/server/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
